DROP DATABASE IF EXISTS SIMPLE;
CREATE DATABASE SIMPLE;
USE SIMPLE;
 
CREATE TABLE PERSONA(
ID_DNI_PERSONA INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDO VARCHAR(20) NOT NULL,
TELEFONO BIGINT NOT NULL,
EMAIL VARCHAR(40) NOT NULL
);
 
CREATE TABLE COMPRADOR(
ID_COMPRADOR INT NOT NULL PRIMARY KEY
);
 
CREATE TABLE VENDEDOR(
ID_VENDEDOR INT NOT NULL PRIMARY KEY
);
 
CREATE TABLE CUENTA(
ID_CUENTA_SIMPLE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
USUARIO VARCHAR(30) NOT NULL,
CONTRASEÑA VARCHAR(20) NOT NULL,
CUENTA_FECHA DATE NOT NULL,
ID_COMPRADOR INT,
ID_VENDEDOR INT,
ID_DNI_PERSONA INT NOT NULL,
CONSTRAINT CUENTA_COMPRADOR FOREIGN KEY (ID_COMPRADOR) REFERENCES COMPRADOR (ID_COMPRADOR) ON DELETE CASCADE,
CONSTRAINT CUENTA_VENDEDOR FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR (ID_VENDEDOR) ON DELETE CASCADE,
CONSTRAINT CUENTA_PERSONA FOREIGN KEY (ID_DNI_PERSONA) REFERENCES PERSONA (ID_DNI_PERSONA) ON DELETE CASCADE
);
 
CREATE TABLE BANCO(
ID_BANCO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TIPO_CUENTA VARCHAR(30) NOT NULL,
NUMERO_CUENTA INT NOT NULL,
ID_CUENTA_SIMPLE INT NOT NULL,
CONSTRAINT BANCO_CUENTA FOREIGN KEY (ID_CUENTA_SIMPLE) REFERENCES CUENTA (ID_CUENTA_SIMPLE) ON DELETE CASCADE
);
 
CREATE TABLE TARJETA(
ID_TARJETA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
BANCO  VARCHAR(30) NOT NULL,
TARJETA_NUMERO INT NOT NULL,
FECHA_VENCIMIENTO DATE NOT NULL,
CODIGO_SEGURIDAD INT NOT NULL,
ID_CUENTA_SIMPLE INT NOT NULL,
CONSTRAINT TARJETA_CUENTA FOREIGN KEY (ID_CUENTA_SIMPLE) REFERENCES CUENTA (ID_CUENTA_SIMPLE) ON DELETE CASCADE
);
 

CREATE TABLE PRODUCTO(
ID_PRODUCTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PRECIO_UNIDAD DECIMAL NOT NULL,
CANTIDAD INT NOT NULL,
ID_VENDEDOR INT NOT NULL,
MARCA VARCHAR(30) NOT NULL,
MODELO VARCHAR(30) NOT NULL,
PRODUCTO_DESCRIPCION VARCHAR(200) NOT NULL,
PRODUCTO_FECHA DATE NOT NULL,
CONSTRAINT PRODUCTO_VENDEDOR FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR (ID_VENDEDOR) ON DELETE CASCADE
);

CREATE TABLE PUBLICACION(
ID_PUBLICACION INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PRODUCTO INT NOT NULL,
PUBLICACION_DESCRIPCION VARCHAR(100) NOT NULL,
ID_VENDEDOR INT NOT NULL,
TITULO VARCHAR(80) NOT NULL,
PUBLICACION_FECHA DATE NOT NULL,
CONSTRAINT PUBLICACION_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO) ON DELETE CASCADE,
CONSTRAINT PUBLICACION_VENDEDOR FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR (ID_VENDEDOR) ON DELETE CASCADE
);



 
CREATE TABLE FACTURA(
ID_FACTURA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PUBLICACION INT NOT NULL,
CANTIDAD_PRODUCTO INT NOT NULL,
PRECIO_SIN_IVA DECIMAL NOT NULL,
PRECIO_TOTAL DECIMAL NOT NULL,
FACTURA_FECHA DATE NOT NULL,
ID_COMPRADOR INT NOT NULL,
ID_VENDEDOR INT NOT NULL,
CONSTRAINT FACTURA_PUBLICACION FOREIGN KEY (ID_PUBLICACION) REFERENCES PUBLICACION (ID_PUBLICACION) ON DELETE CASCADE,
CONSTRAINT FACTURA_COMPRADOR FOREIGN KEY (ID_COMPRADOR) REFERENCES COMPRADOR (ID_COMPRADOR) ON DELETE CASCADE,
CONSTRAINT FACTURA_VENDEDOR FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR (ID_VENDEDOR) ON DELETE CASCADE
);
 
CREATE TABLE VENTA(
ID_VENTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_FACTURA INT NOT NULL,
ID_VENDEDOR INT NOT NULL,
FECHA_VENTA DATE NOT NULL,
CONSTRAINT VENTA_FACTURA FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA (ID_FACTURA) ON DELETE CASCADE,
CONSTRAINT VENTA_VENDEDOR FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR (ID_VENDEDOR) ON DELETE CASCADE
);
 


CREATE TABLE CATEGORIA(
ID_CATEGORIA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TIPO_CATEGORIA VARCHAR(50) NOT NULL
);
 
 
CREATE TABLE PRODUCTO_CATEGORIA(
ID_PRODUCTO_CATEGORIA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PRODUCTO INT NOT NULL,
ID_CATEGORIA INT NOT NULL,
CONSTRAINT PC_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO) ON DELETE CASCADE,
CONSTRAINT PC_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA) ON DELETE CASCADE
);
 


CREATE TABLE CATEGORIA_PUBLICACIONES(
ID_CATEGORIA_PUBLICACION INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PUBLICACION INT NOT NULL,
ID_CATEGORIA INT NOT NULL,
CONSTRAINT CP_PUBLICACION FOREIGN KEY (ID_PUBLICACION) REFERENCES PUBLICACION (ID_PUBLICACION) ON DELETE CASCADE,
CONSTRAINT CP_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA) ON DELETE CASCADE
);
