CREATE OR REPLACE VIEW CUENTA_BANCO AS
SELECT TIPO_CUENTA, NUMERO_CUENTA 
FROM BANCO JOIN CUENTA 
ON BANCO.ID_CUENTA_SIMPLE = CUENTA.ID_CUENTA_SIMPLE 
WHERE CUENTA.ID_CUENTA_SIMPLE = 1;

CREATE OR REPLACE VIEW CUENTA_TARJETA AS
SELECT BANCO, TARJETA_NUMERO, FECHA_VENCIMIENTO, CODIGO_SEGURIDAD
FROM TARJETA JOIN CUENTA 
ON TARJETA.ID_CUENTA_SIMPLE = CUENTA.ID_CUENTA_SIMPLE 
WHERE CUENTA.ID_CUENTA_SIMPLE = 1;

CREATE OR REPLACE VIEW PERSONA_CUENTA AS
SELECT NOMBRE, APELLIDO, TELEFONO, EMAIL
FROM PERSONA JOIN CUENTA 
ON PERSONA.ID_DNI_PERSONA = CUENTA.ID_DNI_PERSONA 
WHERE CUENTA.ID_CUENTA_SIMPLE = 1;

CREATE OR REPLACE VIEW PUBLICACION_CUENTA AS
SELECT * 
FROM PUBLICACION AS PUB JOIN VENDEDOR 
ON PUB.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR 
WHERE VENDEDOR.ID_VENDEDOR  = 1;

CREATE OR REPLACE VIEW PRODUCTO_CUENTA AS
SELECT * 
FROM PRODUCTO JOIN VENDEDOR 
ON PRODUCTO.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR 
JOIN CUENTA
ON VENDEDOR.ID_VENDEDOR = CUENTA.ID_VENDEDOR
JOIN PERSONA 
ON PERSONA.ID_DNI_PERSONA = CUENTA.ID_DNI_PERSONA
WHERE PERSONA.NOMBRE = 'Michel';

